// Config-driven source registry. Adding a source must not require touching
// ingestion control flow. Each Google query maps to a PRIMARY app category.
const makeQueries = (category, terms) => terms.map(q => ({ q, category }));

// Keep queries specific. Google Places text search returns at most 20 results
// per query, so granular family/kid phrases improve coverage and reduce noise.
const TAMPA_FAMILY_GOOGLE_QUERIES = [
  ...makeQueries('fun', [
    "children's museum",
    'kids museum',
    'science museum for kids',
    'aquarium',
    'zoo',
    'wildlife sanctuary',
    'nature center',
    'nature preserve',
    'botanical garden',
    'public library',
    "children's library",
    'library storytime',
    'baby storytime',
    'toddler storytime',
    'playground',
    'park with playground',
    'inclusive playground',
    'indoor playground',
    'indoor play area',
    'soft play',
    'kids play place',
    'play cafe',
    'family friendly cafe',
    'coffee shop with play area',
    'kid friendly restaurant',
    'splash pad',
    'sprayground',
    'water park',
    'family beach',
    'farm with kids activities',
    'petting zoo',
    'mini golf',
    'bowling alley kids',
    'roller skating rink',
    'arcade kids',
    'family entertainment center',
    'trampoline park',
    "children's theater",
    'puppet theater',
    'kids birthday party venue',
  ]),
  ...makeQueries('sports', [
    'swim school for kids',
    'infant swim lessons',
    'toddler swim lessons',
    'kids swimming lessons',
    'gymnastics for kids',
    'toddler gymnastics',
    'mommy and me gymnastics',
    'youth soccer',
    'toddler soccer',
    'kids martial arts',
    'taekwondo for kids',
    'karate for kids',
    'jiu jitsu for kids',
    'kids tennis lessons',
    'youth baseball',
    'youth basketball',
    'kids volleyball',
    'cheerleading for kids',
    'kids ninja gym',
    'rock climbing for kids',
    'ice skating lessons kids',
    'kids sports classes',
  ]),
  ...makeQueries('wellness', [
    'prenatal yoga',
    'postnatal yoga',
    'mommy and me yoga',
    'stroller fitness',
    'mom fitness class',
    'prenatal fitness',
    'postpartum fitness',
    'prenatal massage',
    'postpartum massage',
    'pelvic floor physical therapy',
    'birth center',
    'doula',
    'childbirth classes',
    'parenting classes',
    'breastfeeding support group',
    'postpartum support group',
    'maternal mental health therapist',
    'family counseling',
  ]),
  ...makeQueries('schools', [
    'preschool',
    'pre-k',
    'VPK',
    'Montessori preschool',
    'Reggio Emilia preschool',
    'private preschool',
    'public elementary school',
    'private elementary school',
    'charter elementary school',
    'magnet school',
    'Montessori school',
    'Waldorf school',
    'Catholic school',
    'Christian school',
    'bilingual preschool',
    'special needs school',
    'early learning center',
    'kindergarten',
  ]),
  ...makeQueries('childcare', [
    'daycare',
    'child care center',
    'infant daycare',
    'toddler daycare',
    'preschool daycare',
    'drop in childcare',
    'hourly childcare',
    'backup childcare',
    'after school program',
    'before and after school care',
    'kids aftercare',
    "mother's day out",
    'babysitting service',
    'nanny agency',
    'childcare co-op',
    'kids club childcare',
  ]),
  ...makeQueries('extracurricular', [
    "children's art classes",
    'kids art classes',
    'pottery painting kids',
    'kids music classes',
    'baby music class',
    'toddler music class',
    'mommy and me music',
    'kids dance classes',
    'ballet for kids',
    'kids theater classes',
    "children's acting classes",
    'kids cooking classes',
    'kids coding classes',
    'STEM classes for kids',
    'robotics classes for kids',
    'kids science classes',
    'language classes for kids',
    'Spanish classes for kids',
    'tutoring center kids',
    'math tutoring kids',
    'reading tutoring kids',
    'kids sewing classes',
    'homeschool enrichment',
    'after school enrichment',
    'sensory play classes',
    'mommy and me classes',
  ]),
  ...makeQueries('camps', [
    'summer camp for kids',
    'day camp for kids',
    'spring break camp',
    'winter break camp',
    'holiday camp for kids',
    'STEM summer camp',
    'art summer camp',
    'sports summer camp',
    'swim camp',
    'gymnastics camp',
    'dance camp',
    'theater camp',
    'nature camp',
    'zoo camp',
    'aquarium camp',
    'school break camp',
  ]),
  ...makeQueries('health', [
    'pediatrician',
    'pediatric urgent care',
    "children's urgent care",
    "children's hospital",
    'pediatric dentist',
    'pediatric orthodontist',
    'pediatric optometrist',
    'pediatric eye doctor',
    'pediatric ENT',
    'pediatric allergist',
    'pediatric dermatologist',
    'pediatric physical therapy',
    'pediatric occupational therapy',
    'pediatric speech therapy',
    'pediatric behavioral therapy',
    'ABA therapy kids',
    'child psychologist',
    'child therapist',
    'lactation consultant',
    'breastfeeding clinic',
    'pediatric nutritionist',
    'pediatric chiropractor',
    'family medicine pediatric',
  ]),
];

const TAMPA_DEEP_COVERAGE_GOOGLE_QUERIES = [
  ...makeQueries('fun', [
    'toddler playground',
    'shaded playground',
    'fenced playground',
    'stroller friendly park',
    'park with restrooms',
    'park with picnic area',
    'boardwalk stroller walk',
    'walking trail stroller friendly',
    'kids nature trail',
    'splash park',
    'public pool',
    'community pool',
    'recreation center',
    'community center kids',
    'mall play area',
    "children's bookstore",
    'toy store with events',
    'family friendly farmers market',
    'u-pick farm',
    'strawberry farm',
    'pumpkin patch',
    'family festival venue',
    'kids train ride',
    'kids animal encounter',
    'horseback riding kids',
    'family friendly museum',
    'art museum kids',
    'planetarium',
    'skate park kids',
    'beach with playground',
  ]),
  ...makeQueries('sports', [
    'youth t-ball',
    'youth flag football',
    'youth lacrosse',
    'kids golf lessons',
    'kids cheerleading',
    'kids wrestling',
    'kids fencing',
    'kids archery',
    'kids pickleball',
    'kids skateboarding lessons',
    'kids horseback riding lessons',
    'kids sailing lessons',
    'kids fitness classes',
    'youth track and field',
    'BMX track kids',
    'bike park kids',
    'kids yoga classes',
    'adaptive sports kids',
  ]),
  ...makeQueries('wellness', [
    'prenatal chiropractor',
    'postpartum chiropractor',
    'postpartum doula',
    'new moms group',
    'mom support group',
    'parent support group',
    'infant massage class',
    'babywearing group',
    'postpartum recovery class',
    'perinatal mental health',
    'prenatal class',
    'new parent class',
    'sleep consultant baby',
    'family yoga',
  ]),
  ...makeQueries('schools', [
    'nursery school',
    'co-op preschool',
    'forest school',
    'nature preschool',
    'Spanish immersion preschool',
    'language immersion preschool',
    'special education school',
    'gifted school',
    'elementary charter school',
    'private kindergarten',
    'learning academy',
    'early childhood education',
    'micro school',
    'homeschool academy',
  ]),
  ...makeQueries('childcare', [
    'licensed childcare',
    'family daycare',
    'home daycare',
    'church daycare',
    'faith based daycare',
    'school age childcare',
    'summer childcare',
    'evening childcare',
    'weekend childcare',
    "parent's night out childcare",
    'kids drop off program',
    'childcare with after school pickup',
  ]),
  ...makeQueries('extracurricular', [
    'kids ceramics class',
    'kids painting class',
    'kids craft classes',
    'lego classes for kids',
    'chess classes kids',
    'music lessons kids',
    'piano lessons kids',
    'violin lessons kids',
    'drum lessons kids',
    'voice lessons kids',
    'kids choir',
    'drama classes kids',
    'kids photography classes',
    'kids woodworking class',
    'creative writing kids',
    'debate classes kids',
    'kids swim team',
    'kids garden class',
    'nature classes kids',
    'animal classes kids',
  ]),
  ...makeQueries('camps', [
    'summer day camp',
    'overnight camp',
    'preschool summer camp',
    'toddler summer camp',
    'coding summer camp',
    'robotics summer camp',
    'music summer camp',
    'cheer camp',
    'soccer camp',
    'baseball camp',
    'basketball camp',
    'tennis camp',
    'martial arts camp',
    'vacation bible school',
    'VBS',
    'special needs summer camp',
    'adaptive summer camp',
  ]),
  ...makeQueries('health', [
    'developmental pediatrician',
    'pediatric neurologist',
    'pediatric gastroenterologist',
    'pediatric cardiologist',
    'pediatric endocrinologist',
    'pediatric pulmonologist',
    'pediatric urologist',
    'pediatric orthopedics',
    'pediatric audiologist',
    'kids hearing test',
    'early intervention',
    'feeding therapy',
    'sensory gym',
    'autism therapy',
    'child psychiatry',
    'pediatric sleep clinic',
    'kids vaccine clinic',
    'pediatric ER',
    'pediatric walk in clinic',
  ]),
];

export const SOURCES = [
  {
    id: 'google-places-tampa',
    name: 'Google Places — Tampa family',
    type: 'google_places',
    city: 'Tampa, FL',
    county: 'Hillsborough',
    enabled: true,
    cadenceHours: 168,
    parserVersion: 'v1',
    // locationBias circle ~ Tampa city center, 25km radius.
    bias: { lat: 27.9506, lng: -82.4572, radiusM: 25000 },
    queries: [
      ...TAMPA_FAMILY_GOOGLE_QUERIES,
      ...TAMPA_DEEP_COVERAGE_GOOGLE_QUERIES,
    ],
  },
];

export const getSource = (id) => SOURCES.find(s => s.id === id) || null;

// ----------------------------------------------------------------- event sources
export const EVENT_SOURCES = [
  {
    id: 'eventbrite-tampa-family', name: 'Eventbrite — Tampa family', type: 'eventbrite',
    city: 'Tampa, FL', county: 'Hillsborough', enabled: true, cadenceHours: 24, parserVersion: 'v1',
    queries: [
      { q: 'kids', type: 'class' }, { q: 'toddler', type: 'playgroup' },
      { q: 'storytime', type: 'storytime' }, { q: 'family camp', type: 'camp' },
      { q: 'parenting', type: 'parenting-class' }, { q: 'preschool', type: 'class' },
    ],
  },
  {
    id: 'hcplc-library-ics', name: 'Tampa-Hillsborough Library calendar', type: 'ics',
    city: 'Tampa, FL', county: 'Hillsborough', enabled: false, cadenceHours: 24, parserVersion: 'v1',
    url: '', defaultType: 'library-program',
    notes: 'Set url to the public .ics feed for library storytimes before enabling.',
  },
  {
    id: 'glazer-museum-jsonld', name: "Glazer Children's Museum events", type: 'json_ld',
    city: 'Tampa, FL', county: 'Hillsborough', enabled: false, cadenceHours: 24, parserVersion: 'v1',
    url: 'https://glazermuseum.org/events/', defaultType: 'museum-program',
    notes: 'Verify the events page exposes schema.org Event JSON-LD before enabling.',
  },
  {
    id: 'place-websites', name: 'Place websites — event discovery', type: 'place_website',
    city: 'Tampa, FL', county: 'Hillsborough', enabled: true, cadenceHours: 72, parserVersion: 'v1',
    notes: 'Iterates over DB places with a website; default scans approved places.',
  },
  {
    id: 'fb-graph-tampa-venues', name: 'Facebook Graph — Tampa venues', type: 'facebook_graph',
    city: 'Tampa, FL', county: 'Hillsborough', enabled: false, cadenceHours: 24, parserVersion: 'v1',
    notes: 'Needs an approved Meta app + page tokens; run when META_GRAPH_TOKEN present.',
  },
];

export const getEventSource = (id) => EVENT_SOURCES.find(s => s.id === id) || null;
